name: Backend Deploy

on:
  push: 
    branches:
      - master
      
jobs:
  build: 
    runs-on: self-hosted
    
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy Backend
      run: |
          cd /repository/easyco
          git pull
          composer install
          rm -r -f /var/www/easyco.kopikoding.com/public_html/api/*
          cp -R /repository/easyco/backend/* /var/www/easyco.kopikoding.com/public_html/api/
          cp -R /repository/easyco/backend/public/* /var/www/easyco.kopikoding.com/public_html/api/
