name: Deploy

on:
  push: 
    branches:
      - master
      
jobs:
  build: 
    runs-on: self-hosted
    
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy Backend
      run: |
          cd /var/www
          ls -la
          git pull
          cp /repository/easyco/backend/ /var/www/easyco.kopikoding.com/public_html/api/
